# -*- coding: utf-8 -*-
"""ebcaIFCEdatasetV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJAPW2562FO0Nr7V0mez052KVtcI0WiT
"""

pip install pyswarms

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import shap
import joblib
import os
from typing import Tuple, List, Dict, Any

from scipy.sparse import issparse, hstack, vstack
from scipy.stats import ks_2samp
from sklearn.model_selection import train_test_split, KFold, cross_val_predict
from sklearn.preprocessing import MaxAbsScaler, OneHotEncoder, LabelEncoder
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, f1_score, log_loss
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# Motores de Boosting
from lightgbm import LGBMClassifier
from xgboost import XGBRFClassifier

# PSO para Otimização
import pyswarms as ps

warnings.filterwarnings('ignore')
sns.set(style="whitegrid")

# =====================================================================
# 1. CARREGAMENTO E SPLIT INICIAL (Evitando Data Leakage)
# =====================================================================
def load_and_reshape_data(filepath: str, verbose: bool = True) -> Tuple[pd.DataFrame, pd.Series, List[str]]:
    """Apenas carrega, pivota e separa features do target. NENHUMA estatística é calculada aqui."""
    if verbose: print(f"[1/12] Carregando e estruturando dataset bruto: {filepath}")
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"[ERRO] Arquivo '{filepath}' não encontrado.")

    df = pd.read_csv(filepath)

    if 'Desc_Sit_Matricula' not in df.columns:
        raise ValueError("Coluna 'Desc_Sit_Matricula' não encontrada.")

    status_map = {
        'Formado': 'CONCLUÍDO',
        'Abandono': 'CANCELADO',
        'Cancelado Voluntariamente': 'CANCELADO',
        'Cancelado Compulsoriamente': 'CANCELADO'
    }
    df['status'] = df['Desc_Sit_Matricula'].map(status_map)
    df = df.dropna(subset=['status'])

    subject_cols = ['DESC_DISCIPLINA', 'CARGA_HOR', 'Sit_Disciplina', 'N_FALTAS', 'NOTA', 'Equivalencia']
    student_cols = [c for c in df.columns if c not in subject_cols]

    df_student = df[student_cols].drop_duplicates(subset=['Cod_Pessoa'])
    pivot_df = df.pivot_table(index='Cod_Pessoa', columns='DESC_DISCIPLINA', values='NOTA', aggfunc='max')
    df_merged = df_student.merge(pivot_df, on='Cod_Pessoa', how='inner')

    cols_to_drop_init = ['Cod_Pessoa', 'Desc_Sit_Matricula']
    df_merged = df_merged.drop(columns=[c for c in cols_to_drop_init if c in df_merged.columns])

    X = df_merged.drop(columns=['status'])
    y = df_merged['status']
    subject_names = pivot_df.columns.tolist()

    return X, y, subject_names

def handle_data_leakage(X_train: pd.DataFrame, y_train: np.ndarray, threshold: float = 0.30, verbose: bool = True) -> List[str]:
    """Calcula a Informação Mútua (MI) ESTRITAMENTE nos dados de treino para evitar Leakage."""
    if verbose: print(f"[2/12] Calculando Informação Mútua (MI) apenas no Treino para detectar vazamentos...")

    X_mi = X_train.copy()
    # Preenchimento temporário apenas para o cálculo estatístico do MI
    for col in X_mi.columns:
        if X_mi[col].dtype == 'object':
            X_mi[col] = LabelEncoder().fit_transform(X_mi[col].astype(str))
        else:
            X_mi[col] = X_mi[col].fillna(-1)

    mi_scores = mutual_info_classif(X_mi, y_train, random_state=42)
    mi_series = pd.Series(mi_scores, index=X_mi.columns).sort_values(ascending=False)

    leakage_cols = mi_series[mi_series > threshold].index.tolist()

    if verbose and leakage_cols:
        print(f"      > ATENÇÃO: {len(leakage_cols)} colunas identificadas como vazamento (MI > {threshold}).")
        for col, score in mi_series.head(5).items():
            if score > threshold: print(f"        - {col}: {score:.4f}")

    return leakage_cols

def build_and_fit_pipeline(X_train: pd.DataFrame, verbose: bool = True) -> Tuple[ColumnTransformer, List[str]]:
    """Constrói e ajusta o pipeline de preprocessamento ESTRITAMENTE nos dados de treino."""
    if verbose: print("[4/12] Ajustando Scikit-Learn Pipeline (Imputer e Scaler) apenas no Treino...")

    cat_cols = X_train.select_dtypes(include=['object', 'category']).columns
    num_cols = X_train.select_dtypes(include=['number']).columns

    # As medianas numéricas serão aprendidas APENAS no X_train
    num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', MaxAbsScaler())
    ])

    cat_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='constant', fill_value='Não Informado')),
        ('encoder', OneHotEncoder(sparse_output=True, handle_unknown='ignore'))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', num_pipeline, num_cols),
            ('cat', cat_pipeline, cat_cols)
        ],
        remainder='drop'
    )

    preprocessor.fit(X_train)
    expected_features = X_train.columns.tolist()
    return preprocessor, expected_features

# =====================================================================
# 2. ARQUITETURA EBCA + DEEP FOREST (Lógica mantida original)
# =====================================================================
def extended_balance_cascade(X, y, T=5, imbalance_ratio=2.5, verbose=False):
    classes, counts = np.unique(y, return_counts=True)
    min_class, maj_class = classes[np.argmin(counts)], classes[np.argmax(counts)]
    idx_min, idx_maj = np.where(y == min_class)[0], np.where(y == maj_class)[0]

    P_X, P_y = X[idx_min], y[idx_min]
    N_X, N_y = X[idx_maj], y[idx_maj]
    subsets = []

    for i in range(T):
        if len(idx_maj) == 0 or (len(idx_maj) / len(idx_min)) < imbalance_ratio: break
        sample_idx = np.random.choice(len(idx_maj), size=len(idx_min), replace=False)
        N_i_X, N_i_y = N_X[sample_idx], N_y[sample_idx]

        X_train_c = vstack([P_X, N_i_X]) if issparse(P_X) else np.vstack([P_X, N_i_X])
        y_train_c = np.concatenate([P_y, N_i_y])

        clf = DecisionTreeClassifier(max_depth=3, random_state=42+i)
        clf.fit(X_train_c, y_train_c)

        preds = clf.predict(N_X)
        correctly_classified_maj = (preds == maj_class)
        N_X, N_y = N_X[~correctly_classified_maj], N_y[~correctly_classified_maj]
        idx_maj = np.arange(len(N_y))

        S_i_X = vstack([P_X, N_X]) if issparse(P_X) else np.vstack([P_X, N_X])
        S_i_y = np.concatenate([P_y, N_y])
        subsets.append((S_i_X, S_i_y))

    if not subsets:
        S_i_X = vstack([P_X, N_X]) if issparse(P_X) else np.vstack([P_X, N_X])
        subsets.append((S_i_X, np.concatenate([P_y, N_y])))

    return subsets

class EBCADeepCascadeForest(BaseEstimator, ClassifierMixin):
    def __init__(self, max_layers=5, k_fold=3, T=3, imbalance_ratio=2.5, lgbm_num_leaves=127, xgb_max_depth=10, random_state=42):
        self.max_layers = max_layers
        self.k_fold = k_fold
        self.T = T
        self.imbalance_ratio = imbalance_ratio
        self.lgbm_num_leaves = lgbm_num_leaves
        self.xgb_max_depth = xgb_max_depth
        self.random_state = random_state
        self.ebca_estimators_ = []
        self.layers_ = []
        self.best_layer_num_ = 0

    def _get_ebca_estimators(self, idx):
        lgbm = LGBMClassifier(boosting_type='rf', num_leaves=max(31, self.lgbm_num_leaves//2), bagging_fraction=0.8, bagging_freq=1, feature_fraction=0.8, n_estimators=100, random_state=self.random_state + idx, n_jobs=-1, verbose=-1)
        xgb = XGBRFClassifier(n_estimators=100, max_depth=max(3, self.xgb_max_depth-2), subsample=0.8, colsample_bynode=0.8, random_state=self.random_state + idx + 100, n_jobs=-1, eval_metric='logloss')
        return lgbm, xgb

    def _get_layer_estimators(self, layer_idx):
        lgbm_rf = LGBMClassifier(boosting_type='rf', num_leaves=self.lgbm_num_leaves, n_estimators=100, bagging_fraction=0.8, bagging_freq=1, feature_fraction=0.8, n_jobs=-1, verbose=-1, random_state=self.random_state + layer_idx * 10 + 1)
        xgb_rf = XGBRFClassifier(n_estimators=100, max_depth=self.xgb_max_depth, subsample=0.8, colsample_bynode=0.8, n_jobs=-1, eval_metric='logloss', random_state=self.random_state + layer_idx * 10 + 2)
        return [lgbm_rf, xgb_rf]

    def fit(self, X, y, verbose=False):
        # Treino interno da Deep Forest
        X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=self.random_state, stratify=y)
        subsets = extended_balance_cascade(X_train, y_train, T=self.T, imbalance_ratio=self.imbalance_ratio, verbose=verbose)

        self.ebca_estimators_ = []
        train_ebca_probas, val_ebca_probas = [], []

        for i, (X_sub, y_sub) in enumerate(subsets):
            lgbm, xgb = self._get_ebca_estimators(i)
            lgbm.fit(X_sub, y_sub)
            xgb.fit(X_sub, y_sub)
            self.ebca_estimators_.extend([lgbm, xgb])
            train_ebca_probas.extend([lgbm.predict_proba(X_train), xgb.predict_proba(X_train)])
            val_ebca_probas.extend([lgbm.predict_proba(X_val), xgb.predict_proba(X_val)])

        train_ebca_concat = np.hstack(train_ebca_probas)
        val_ebca_concat = np.hstack(val_ebca_probas)

        X_train_current = hstack([X_train, train_ebca_concat]) if issparse(X_train) else np.hstack([X_train, train_ebca_concat])
        X_val_current = hstack([X_val, val_ebca_concat]) if issparse(X_val) else np.hstack([X_val, val_ebca_concat])

        self.layers_ = []
        best_val_score = -np.inf

        for layer_idx in range(self.max_layers):
            estimators = self._get_layer_estimators(layer_idx)
            cv = KFold(n_splits=self.k_fold, shuffle=True, random_state=self.random_state)
            layer_train_probas, layer_val_probas = [], []

            for est in estimators:
                oof_probas = cross_val_predict(est, X_train_current, y_train, cv=cv, method='predict_proba', n_jobs=-1)
                layer_train_probas.append(oof_probas)
                est.fit(X_train_current, y_train)
                layer_val_probas.append(est.predict_proba(X_val_current))

            avg_val_probas = np.mean(layer_val_probas, axis=0)
            current_val_score = roc_auc_score(y_val, avg_val_probas[:, 1])

            if current_val_score <= best_val_score: break

            best_val_score = current_val_score
            self.layers_.append(estimators)
            self.best_layer_num_ = layer_idx + 1

            train_probas_concat = np.hstack(layer_train_probas)
            val_probas_concat = np.hstack(layer_val_probas)

            if issparse(X_train_current):
                X_train_current = hstack([X_train_current, train_probas_concat])
                X_val_current = hstack([X_val_current, val_probas_concat])
            else:
                X_train_current = np.hstack([X_train_current, train_probas_concat])
                X_val_current = np.hstack([X_val_current, val_probas_concat])

        return self

    def transform_to_last_layer(self, X):
        X_current = X.copy()
        ebca_probas = [est.predict_proba(X_current) for est in self.ebca_estimators_]
        X_current = hstack([X_current, np.hstack(ebca_probas)]) if issparse(X_current) else np.hstack([X_current, np.hstack(ebca_probas)])

        for layer_idx in range(len(self.layers_) - 1):
            layer_probas = [est.predict_proba(X_current) for est in self.layers_[layer_idx]]
            X_current = hstack([X_current, np.hstack(layer_probas)]) if issparse(X_current) else np.hstack([X_current, np.hstack(layer_probas)])

        return X_current.tocsr() if issparse(X_current) else X_current

    def predict_proba(self, X):
        X_current = self.transform_to_last_layer(X)
        last_layer_probas = [est.predict_proba(X_current) for est in self.layers_[-1]]
        return np.mean(last_layer_probas, axis=0)

    def predict(self, X):
        return np.argmax(self.predict_proba(X), axis=1)

# =====================================================================
# 3. OTIMIZAÇÃO PSO E PERSISTÊNCIA
# =====================================================================
def optimize_hyperparams(params, X_tr, y_tr, X_v, y_v):
    scores = []
    for param in params:
        t_val = max(1, int(round(param[0])))
        lgbm_leaves = max(31, int(round(param[1])))
        xgb_depth = max(3, int(round(param[2])))

        model = EBCADeepCascadeForest(max_layers=2, k_fold=3, T=t_val, lgbm_num_leaves=lgbm_leaves, xgb_max_depth=xgb_depth, random_state=42)
        model.fit(X_tr, y_tr, verbose=False)
        preds = model.predict_proba(X_v)[:, 1]
        auc = roc_auc_score(y_v, preds)
        scores.append(1.0 - auc)
    return np.array(scores)

def save_model_artifacts(model, preprocessor, le, expected_features, subject_names, leakage_cols, filepath='modelo_evasao_artifacts.pkl'):
    print(f"\n[EXPORT] Salvando modelo e artefatos de pré-processamento em: {filepath}")
    artifacts = {
        'model': model,
        'preprocessor': preprocessor,
        'label_encoder': le,
        'expected_features': expected_features,
        'subject_names': subject_names,
        'leakage_cols': leakage_cols # Importante salvar para limpar dados novos
    }
    joblib.dump(artifacts, filepath)
    print("      > Exportação concluída com sucesso!")

def load_model_artifacts(filepath='modelo_evasao_artifacts.pkl') -> dict:
    return joblib.load(filepath)

# =====================================================================
# 4. SISTEMA EM PRODUÇÃO (INFERÊNCIA PARA NOVOS ALUNOS)
# =====================================================================
def predict_new_students(new_filepath: str, artifacts_filepath: str = 'modelo_evasao_artifacts.pkl'):
    artifacts = load_model_artifacts(artifacts_filepath)
    model, preprocessor, expected_features = artifacts['model'], artifacts['preprocessor'], artifacts['expected_features']
    subject_names, leakage_cols = artifacts['subject_names'], artifacts['leakage_cols']

    print(f"\n[PRODUÇÃO] Processando arquivo de novos alunos: {new_filepath}")
    df = pd.read_csv(new_filepath)
    subject_cols = ['DESC_DISCIPLINA', 'CARGA_HOR', 'Sit_Disciplina', 'N_FALTAS', 'NOTA', 'Equivalencia']
    student_cols = [c for c in df.columns if c not in subject_cols]
    df_student = df[student_cols].drop_duplicates(subset=['Cod_Pessoa'])

    if 'DESC_DISCIPLINA' in df.columns and 'NOTA' in df.columns:
        pivot_df = df.pivot_table(index='Cod_Pessoa', columns='DESC_DISCIPLINA', values='NOTA', aggfunc='max')
        df_merged = df_student.merge(pivot_df, on='Cod_Pessoa', how='left')
    else:
        df_merged = df_student.copy()

    # Aplica os expurgos descobertos no treinamento
    df_merged = df_merged.drop(columns=[c for c in leakage_cols if c in df_merged.columns])

    for col in expected_features:
        if col not in df_merged.columns:
            # Disciplina não cursada recebe 0. Demais features faltantes receberão np.nan e serão tratadas pela Mediana do Treino.
            df_merged[col] = 0.0 if col in subject_names else np.nan

    X_new = df_merged[expected_features]
    X_new_processed = preprocessor.transform(X_new)

    probabilidades = model.predict_proba(X_new_processed)[:, 1]
    resultados = pd.DataFrame({'Cod_Pessoa': df_merged['Cod_Pessoa'], 'Chance_Evasao_Perc': probabilidades * 100})
    resultados['Risco'] = np.where(resultados['Chance_Evasao_Perc'] > 50.0, 'ALTO RISCO (Evasão)', 'BAIXO RISCO (Conclusão)')

    print("\n      > Predições Finalizadas! Amostra do Sistema de IA:")
    print(resultados.head(10).to_string(index=False))
    return resultados

# =====================================================================
# EXECUÇÃO PRINCIPAL DO PIPELINE (SEM DATA LEAKAGE)
# =====================================================================
if __name__ == "__main__":
    arquivo_treino = 'ifce_telecom_unificado - ifce_telecom_unificado.csv'

    try:
        # 1. Carrega e estrutura sem calcular nada estatístico
        X_raw, y_raw, subject_names = load_and_reshape_data(arquivo_treino, verbose=True)

        # 2. Codifica o Target (Seguro fazer globalmente pois é uma regra de negócio clara)
        le = LabelEncoder()
        y_encoded = le.fit_transform(y_raw)

        # 3. TRAIN TEST SPLIT (AGORA LOGO NO INÍCIO)
        X_train, X_test, y_train, y_test = train_test_split(X_raw, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)
        print("[3/12] Train/Test Split realizado garantindo a segregação dos dados.")

        # 4. Lida com Data Leakage calculando MI estritamente no Treino
        leakage_cols = handle_data_leakage(X_train, y_train, threshold=0.30)
        X_train = X_train.drop(columns=leakage_cols)
        X_test = X_test.drop(columns=[c for c in leakage_cols if c in X_test.columns])

        # 5. Preenche ausência de disciplinas com zero (Apenas regra de negócio, sem Leakage)
        for col in subject_names:
            if col in X_train.columns: X_train[col] = X_train[col].fillna(0)
            if col in X_test.columns: X_test[col] = X_test[col].fillna(0)

        # 6. Cria o Pipeline estatístico (Apenas aprendendo do Treino)
        preprocessor, expected_features = build_and_fit_pipeline(X_train)

        print("[5/12] Transformando dados de treino e teste...")
        X_train_processed = preprocessor.transform(X_train)
        X_test_processed = preprocessor.transform(X_test)

        # 7. Otimização Global com PSO (Agora mais denso)
        print("\n[6/12] Iniciando PSO Multiparametrizado (T, Num_Leaves, Max_Depth)...")
        # Criando o split interno para o PSO a partir do treino processado
        X_tr_pso, X_val_pso, y_tr_pso, y_val_pso = train_test_split(X_train_processed, y_train, test_size=0.25, random_state=42, stratify=y_train)

        bounds = (np.array([1.0, 31.0, 3.0]), np.array([8.0, 255.0, 15.0]))
        # AUMENTADO: de 5 partículas para 15, de 3 iterações para 10.
        optimizer = ps.single.GlobalBestPSO(n_particles=15, dimensions=3, options={'c1': 0.5, 'c2': 0.3, 'w': 0.9}, bounds=bounds)
        cost, pos = optimizer.optimize(optimize_hyperparams, iters=10, X_tr=X_tr_pso, y_tr=y_tr_pso, X_v=X_val_pso, y_v=y_val_pso, verbose=True)

        best_T, best_num_leaves, best_max_depth = int(round(pos[0])), int(round(pos[1])), int(round(pos[2]))
        print(f"\n[7/12] PSO Finalizado! Hiperparâmetros ideais: T={best_T} | Folhas_LGBM={best_num_leaves} | Depth_XGB={best_max_depth}")

        # 8. Instanciando e Treinando o Modelo Final
        print("\n[8/12] Instanciando a Deep Forest Otimizada...")
        ebca_model = EBCADeepCascadeForest(max_layers=5, T=best_T, lgbm_num_leaves=best_num_leaves, xgb_max_depth=best_max_depth)
        ebca_model.fit(X_train_processed, y_train, verbose=True)

        # 9. Avaliação (Opcional, mas você já possui os métodos de plot)
        auc_score = roc_auc_score(y_test, ebca_model.predict_proba(X_test_processed)[:, 1])
        print(f"\n[12/12] AUC no conjunto de teste estrito (Sem Leakage): {auc_score:.4f}")

        # 10. Exportar Tudo!
        save_model_artifacts(ebca_model, preprocessor, le, expected_features, subject_names, leakage_cols, filepath='modelo_evasao_v2.pkl')

    except FileNotFoundError:
        print("Arquivo de treino não encontrado, pule a execução para simular a predição se quiser.")

resultados_finais = predict_new_students(
    new_filepath='dados_da_nova_turma.csv',
    artifacts_filepath='modelo_evasao_v1.pkl'
)
resultados_finais.to_csv('relatorio_de_risco.csv')
